apiVersion: apps/v1
kind: Deployment
metadata:
  name: doorboard-deployment
  labels:
    app: doorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doorboard
  template:
    metadata:
      labels:
        app: doorboard
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /app/data"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      containers:
      - name: doorboard
        image: harbor.cu.ac.kr/doorboard/doorboard:latest # Replace with your actual image name/registry
        imagePullPolicy: IfNotPresent # Useful for local testing
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: doorboard-pvc

