apiVersion: v1
kind: PersistentVolume
metadata:
  name: doorboard-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/doorboard" # Path on the host node
    type: DirectoryOrCreate
