apiVersion: v1
kind: Service
metadata:
  name: doorboard-service
spec:
  selector:
    app: doorboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080 # Optional: Fixed NodePort for easier access
  type: NodePort # Using NodePort for easy access without Ingress Controller setup
